version: "3"

services:
  fastapi:
    build: .
    container_name: fastapi-book-project
    ports:
      - "8000:8000"

  nginx:
    build: ./proxy
    container_name: nginx_service
    ports:
      - "80:80"
    depends_on:
      - fastapi
