name: Deploy FastAPI to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to AWS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /var/www/fastapi-book-project  # Navigate to project directory
            sudo git pull origin main  # Pull latest changes
            source env/bin/activate  # Activate virtual environment
            sudo env/bin/python -m pip install -r requirements.txt  # Install dependencies
            sudo supervisorctl restart all  # Restart FastAPI server
