name: Deploy FastAPI

on:
  workflow_dispatch: # Enables manual execution from GitHub Actions
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    name: Deploy FastAPI App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PM2 (if not already installed)
        run: |
          sudo npm install -g pm2

      - name: Restart FastAPI Server
        run: |
          pm2 restart fastapi || pm2 start "uvicorn main:app --uds=/tmp/uvicorn.sock" --name fastapi