name: Deploy FastAPI

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    name: Deploy FastAPI App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restart FastAPI Server
        run: |
          pm2 restart fastapi || pm2 start "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4" --name fastapi
